###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: laravel5angular6-memcached

    redis:
      image: redis:alpine
      container_name: laravel5angular6-redis

    mysql:
      image: mysql:8.0
      container_name: laravel5angular6-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravelangularbook
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8284:3306"

    elasticsearch:
      image: elasticsearch:5.4-alpine
      container_name: laravel5angular6-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: laravel5angular6-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8282:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: laravel5angular6-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

